# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    groups:
      prod-deps:
        dependency-type: 'production'
        exclude-patterns:
          - '@angular*'
      dev-deps:
        dependency-type: 'development'
        exclude-patterns:
          - '@angular*'
      angular-deps:
        patterns:
          - '@angular*'
